FROM python:3.11-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt 

COPY server.py .

COPY . .

RUN useradd -m appuser

USER appuser

CMD ["python", "server.py"]
